services:
  - type: web
    name: ind-money-api
    runtime: docker
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: RECIPIENT_NAME
        sync: false
      - key: RECIPIENT_EMAIL
        sync: false
